import 'reflect-metadata'
import './parts/health/controller/HealthController'
import './parts/com/controller/PingController'
import './parts/sample/controller/SampleController'
import './parts/user/controller/UsersController'
